const express = require("express");
const passport = require("./config/passport");
const userController = require("./controllers/user.controller");
const projectController = require("./controllers/project.controller");
const recommendationController = require("./controllers/recommendation.controller");
const { register, login } = require("./controllers/auth.controller");
const githubAuth = require("./utils/githubAuth");
const app = express();
app.use(express.json());
app.use(passport.initialize());
app.use("/auth/github", githubAuth);
app.use("/recommendations", recommendationController);
app.use("/users", userController);
app.use("/projects", projectController);
app.post("/register", register);
app.post("/login", login);
module.exports = app;
